apiVersion: 1
datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    jsonData:
      maxLines: 1000
  - name: Jaeger
    type: jaeger
    url: http://jaeger-query:16686
    access: proxy
    isDefault: false
